name: Translate Readme Action
author: Ephraim Atta-Duncan
description: Translate the Readme to another language

inputs:
  LANG:
    description: 'The Language you want to translate to'
    required: false
    default: 'zh-CN'
  OUTPUT_DIR:
    description: 'The output dictionary you want to save'
    required: false
    default: '.'
  OUTPUT_FILE:
    description: 'The output file you want to save, can use `${lang}` to replace with the language'
    required: false
    default: 'README.${lang}.md'


runs:
  using: 'node12'
  main: 'dist/index.js'

branding:
  icon: book-open
  color: black
